In [1]:
! pip install tensorflow


In [2]:
pip install --upgrade keras

Note: you may need to restart the kernel to use updated packages.


In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
## Define the vocabulary size
voc_size=10000

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
# one hot representation 
one_hot_rep=[one_hot(words,voc_size)for words in sent]
one_hot_rep

[[1782, 1650, 9799, 7342],
 [1782, 1650, 9799, 2670],
 [1782, 1397, 9799, 439],
 [75, 6778, 7306, 19, 2593],
 [75, 6778, 7306, 19, 959],
 [8021, 1782, 5078, 9799, 4532],
 [8977, 4146, 5358, 19]]

In [9]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)


[[   0    0    0    0 1782 1650 9799 7342]
 [   0    0    0    0 1782 1650 9799 2670]
 [   0    0    0    0 1782 1397 9799  439]
 [   0    0    0   75 6778 7306   19 2593]
 [   0    0    0   75 6778 7306   19  959]
 [   0    0    0 8021 1782 5078 9799 4532]
 [   0    0    0    0 8977 4146 5358   19]]


In [12]:
#feature representation
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step


array([[[-4.07544523e-03,  3.08449604e-02,  3.35197523e-03,
          1.63113512e-02, -1.72197595e-02, -1.36617199e-02,
          8.22455809e-03,  9.23106819e-03,  4.46573384e-02,
         -4.51941490e-02],
        [-4.07544523e-03,  3.08449604e-02,  3.35197523e-03,
          1.63113512e-02, -1.72197595e-02, -1.36617199e-02,
          8.22455809e-03,  9.23106819e-03,  4.46573384e-02,
         -4.51941490e-02],
        [-4.07544523e-03,  3.08449604e-02,  3.35197523e-03,
          1.63113512e-02, -1.72197595e-02, -1.36617199e-02,
          8.22455809e-03,  9.23106819e-03,  4.46573384e-02,
         -4.51941490e-02],
        [-4.07544523e-03,  3.08449604e-02,  3.35197523e-03,
          1.63113512e-02, -1.72197595e-02, -1.36617199e-02,
          8.22455809e-03,  9.23106819e-03,  4.46573384e-02,
         -4.51941490e-02],
        [-1.71579607e-02,  1.42115019e-02,  1.92670859e-02,
         -4.41040993e-02,  2.87097953e-02,  4.69161905e-02,
          9.17525217e-03, -5.88095188e-03, -4.964876