In [118]:
! pip install tensorflow


In [100]:
pip install --upgrade keras

Note: you may need to restart the kernel to use updated packages.


In [101]:
from tensorflow.keras.preprocessing.text import one_hot

In [102]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [103]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [119]:
## Define the vocabulary size
voc_size=10000

In [105]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [106]:
# one hot representation 
one_hot_rep=[one_hot(words,voc_size)for words in sent]
one_hot_rep

[[6109, 1669, 8851, 7573],
 [6109, 1669, 8851, 6920],
 [6109, 4127, 8851, 6400],
 [4234, 5545, 384, 8643, 5894],
 [4234, 5545, 384, 8643, 4542],
 [7468, 6109, 5432, 8851, 7471],
 [5966, 8771, 7781, 8643]]

In [107]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [108]:
import numpy as np

In [109]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)


[[   0    0    0    0 6109 1669 8851 7573]
 [   0    0    0    0 6109 1669 8851 6920]
 [   0    0    0    0 6109 4127 8851 6400]
 [   0    0    0 4234 5545  384 8643 5894]
 [   0    0    0 4234 5545  384 8643 4542]
 [   0    0    0 7468 6109 5432 8851 7471]
 [   0    0    0    0 5966 8771 7781 8643]]


In [110]:
#feature representation
dim=10

In [111]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [117]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step


array([[[ 3.45201828e-02,  1.18079074e-02, -1.73952356e-02,
          2.37411000e-02,  2.23180987e-02, -4.42491844e-03,
          1.09983310e-02, -5.10990620e-03,  4.01685275e-02,
          4.98226322e-02],
        [ 3.45201828e-02,  1.18079074e-02, -1.73952356e-02,
          2.37411000e-02,  2.23180987e-02, -4.42491844e-03,
          1.09983310e-02, -5.10990620e-03,  4.01685275e-02,
          4.98226322e-02],
        [ 3.45201828e-02,  1.18079074e-02, -1.73952356e-02,
          2.37411000e-02,  2.23180987e-02, -4.42491844e-03,
          1.09983310e-02, -5.10990620e-03,  4.01685275e-02,
          4.98226322e-02],
        [ 3.45201828e-02,  1.18079074e-02, -1.73952356e-02,
          2.37411000e-02,  2.23180987e-02, -4.42491844e-03,
          1.09983310e-02, -5.10990620e-03,  4.01685275e-02,
          4.98226322e-02],
        [-2.08592303e-02,  2.12338306e-02,  2.97911465e-05,
          2.83903368e-02, -4.00596038e-02, -1.85633190e-02,
         -1.66591257e-03,  1.18368752e-02, -1.357687